### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by keyganker** [oraoto/php-stacktrace#1]
rust新手，运行cargo build的时候报错，如下：
![feature] may not be used on the stable release channel

#![feature(try_from)]

查资料说是因为我的rustc是stable的？难道要用一个nightly的？

**Comment by oraoto** [comment]
是的，需要nightly，我用的是`1.22.0-nightly (930d3b17d 2017-09-26)`，最新的应该也没问题。

**Comment by keyganker** [comment]
嗯 刚好下载了一个nightly的编过了，多谢
